### ISSUE TITLE
Allow archive to S3

### ISSUE THREAD

**Issue by paddatrapper** [jooola/earhorn#23]
It would be great to be able to archive to an S3 compatible bucket, as archive storage can get large. My use-case would be running Earhorn in the cloud, monitoring the stream with the archive accessible for production staff to pull logs, proofs, create stings, etc. This is much more cost effective when using object storage instead of block storage for large volumes of data.

**Comment by jooola** [comment]
I don't use an object storage for the generated archives, but this is definitely a good idea, I might even consider use it if I implement it.

For now, I have a second script that organize and send the archives files to a external storage server. I though at first it wasn't the job for this tool, but with a S3 upload mechanism embed in earhorn maybe I can bring my own scripts here.

**Comment by jooola** [comment]
Good morning @loydbanks !

> Good morning, my manager Mr Robbertze asked that if possible, may we please
> work together for the upload to s3 for earhorn. I had a few ideas on my
> side that I can share if you are interested. Please share a strategy which
> you would accept for getting this issue resolved.
>
> For me I was thinking of having a function that uploads to  an s3 bucket.
> We will check if a new file has been successfully created locally then we
> can upload and clear the folder after we successfully upload.
> If you're interested, may I please have a meeting with you, maybe today or
> tomorrow just to discuss things further.
> Kind regards
> Lonwabo Zaula

I am happy to discuss the best way we can implement this. Tell me where we can have this discussion, I would say on chat.libretime.org if you already have an account there. Otherwise you can reach me on Matrix/Signal/Telegram. Or directly on this issue ticket I don't mind writing here. Tell me, I'll be around.

Jo
