### ISSUE TITLE
Allow to transcode the stream in a different storage format

### ISSUE THREAD

**Issue by loydbanks** [jooola/earhorn#35]
The format option for the stored files does not work. 
Example: --archive-path=/home/ --archive-segment-format=mp3 https://example.stream

This will not work as it does not store the stream as mp3 files

**Comment by jooola** [comment]
Fixed in v0.5.2

Thanks for the issue!

**Comment by loydbanks** [comment]
Hello.

The issue is with the -c copy, which assumes that the source and
destination have the same format (mp3). In our case this is not true. We
stream in ogg, but archive in mp3. So the -c copy should not be present.
Ideally we should be able to configure the format in which we archive, but
that would be an additional extension. So the issue I would like to raise
is the assumption that the stream and archive will always be the same
format, can we get that?

**Comment by jooola** [comment]
Having the -copy flag reduce CPU usage a lot, and since I personally don't need to transcode the stream in a different format, this seemed obvious to add the flag. But I see your use case.

I think we could add a flag that specify the stream format and if the stream is in a different format, remove the copy flag.

**Comment by paddatrapper** [comment]
Yeah, that sounds reasonable. It can default to the same format as the archive (and so add `-c copy`), but remove it if different.

**Comment by loydbanks** [comment]
Good morning, my manager Mr Robbertze asked that if possible, may we please
work together for the upload to s3 for earhorn. I had a few ideas on my
side that I can share if you are interested. Please share a strategy which
you would accept for getting this issue resolved.

For me I was thinking of having a function that uploads to  an s3 bucket.
We will check if a new file has been successfully created locally then we
can upload and clear the folder after we successfully upload.

If you're interested, may I please have a meeting with you, maybe today or
tomorrow just to discuss things further.

Kind regards
Lonwabo Zaula

**Comment by paddatrapper** [comment]
@loydbanks perhaps discuss this on #23?

**Comment by loydbanks** [comment]
Good morning. I am on Matrix and was wondering if I could get your username
and give you an invite and we can set up a meeting there.

Enjoy the rest of your day.

Kind regards
Lonwabo Zaula

**Comment by jooola** [comment]
@joola
